networks:
  cryze_network:
    driver: bridge

services:
  cryze_api:
    restart: unless-stopped
    networks:
      - cryze_network
    build:
      context: ./cryze_api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env

  cryze_android_app:
    restart: unless-stopped
    networks:
      - cryze_network
    build:
      context: ./cryze_android_app
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 5555:5555
    entrypoint: # need to override the entrypoint to run the app on arch, see the redroid docs
      - /init
      - qemu=1
      - androidboot.hardware=redroid
      - androidboot.use_memfd=1
      - androidboot.redroid_net_ndns=1
      - androidboot.redroid_net_dns1=127.0.0.11
      - androidboot.redroid_gpu_mode=host
      - androidboot.redroid_gpu_node=/dev/dri/renderD128
